### ISSUE TITLE
Android picker breaking with minimum date, maximum date, and timezone offset combo

### ISSUE THREAD

**Issue by endlo** [henninghall/react-native-date-picker#190]
**Describe the bug**
When providing props for `minimumDate`, `maximumDate`, and `timeZoneOffsetInMinutes`, the Android interface flips to the minimum date on any change and doesn't fire the `onDateChange` function. Everything works correctly on iOS. If I remove any of the props individually, everything works, it only seems to break with the combo of all three.

**Expected behavior**
The Android interface should flip to the new date/time and call `onDateChange`.

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
export default class App extends Component {

  state = { date: new Date() }

  render = () =>
    <DatePicker
      date={this.state.date}
      onDateChange={date => this.setState({ date })}
      minimumDate=[any minimum date]
      maximumDate=[date on the same day as the minimum]
      timeZoneOffsetInMinutes=-240
    />

}
```

**Smartphone (please complete the following information):**
 - OS: Android
 - React Native version 0.61.4
 - react-native-date-picker version 2.7.10

**Comment by endlo** [comment]
Some follow up on this: we're only noticing this happen on Android 8.0 or later. Just tested with a device running Android 7.0 and the picker works but lists an option for a date that is invalid. Added a screenshot below. Sunday is not a valid date to choose as it is prior to the minimum date. On devices 8.0 or later, the only option is Sunday and "Today" (which is as of Monday May 18th) is not available to choose:
<img width="337" alt="image" src="https://user-images.githubusercontent.com/34322533/82266857-aafd8a00-991f-11ea-9e07-87fce1ce4785.png">

**Comment by endlo** [comment]
Even more context: this seems to only be the case when the minimum and maximum dates are on the same day and the mode is `datetime`.

**Comment by henninghall** [comment]
Thanks a lot for your explanation, sorry for taking some time but I will look into it.

**Comment by ospfranco** [comment]
We are facing some related issue, only android, when maxDate, minDate and offset are set, you can try to select a minute which is larger than the maxDate, the component resets fine most of the time, but every once in a while it doesn't so you are able to select a date greater than the maxDate (or minDate), it happens randomly though, so it might be some sort of race condition in the android implementation of the component.

**Comment by henninghall** [comment]
Seems like there are a few different issues here. I found a situation were onChange didn't trigger when exceding min/max dates. This problem has been fixed in v3.0.2. 

@endlo If you can reproduce the "extra visible day"-problem it would be great if you could send me the code. I didn't manage to reproduce by your initial code sample. I could only reproduce the "onChange trigger" problem from that. 

@ospfranco Sounds like this could be connected to "the onChange trigger" problem but it could also be something else. Please let me know if you see it again after upgrading to version `3.0.2`

**Comment by henninghall** [comment]
Let me know if your issues exist in the new version and we can repoen the issue

**Comment by randhi-w** [comment]
This issue still occurs in react-native-datepicker 4.2.10, which seems to be recreated when the mode is in 'dateTime' and both the timeZoneOffsetInMinutes and maximumDate props are given. Further, I noticed that adding an extra 21 hrs to maximumDate from the passedDate works fine.
