### ISSUE TITLE
IllegalArgumentException crash on Android

### ISSUE THREAD

**Issue by Trex28** [henninghall/react-native-date-picker#301]
**Describe**
Since upgrading to RN 0.64 we encounter following crash on Android

The weird part here is that in our project we use `react-native-gesture-handle` in other components but when we scroll to change the date from `DatePickerField` it starts to crash on Android and the log points out crash because of `react-native-gesture-handler`. I am not sure that i am right if i post this issue in here but in fact there are maybe related things between `DatePickerField` with this crash.

Crash log:

IllegalArgumentException. Unable to find JSIModule for class UIManager

```
java.lang.IllegalArgumentException: 
  at com.facebook.react.bridge.JSIModuleRegistry.getModule (JSIModuleRegistry.java:39)
  at com.facebook.react.bridge.CatalystInstanceImpl.getJSIModule (CatalystInstanceImpl.java:2)
  at com.facebook.react.uimanager.UIManagerHelper.getUIManager (UIManagerHelper.java:81)
  at com.facebook.react.uimanager.UIManagerHelper.getUIManager (UIManagerHelper.java:1)
  at com.facebook.react.uimanager.UIManagerHelper.getUIManagerForReactTag (UIManagerHelper.java:4)
  at com.facebook.react.animated.NativeAnimatedNodesManager.handleEvent (NativeAnimatedNodesManager.java:17)
  at com.facebook.react.animated.NativeAnimatedNodesManager.onEventDispatch (NativeAnimatedNodesManager.java:6)
  at com.facebook.react.uimanager.events.EventDispatcherImpl.dispatchEvent (EventDispatcherImpl.java:27)
  at com.facebook.react.uimanager.JSTouchDispatcher.handleTouchEvent (JSTouchDispatcher.java:58)
  at com.facebook.react.ReactRootView.dispatchJSTouchEvent (ReactRootView.java:49)
  at com.facebook.react.ReactRootView.onInterceptTouchEvent (ReactRootView.java)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2753)
  at com.swmansion.gesturehandler.react.RNGestureHandlerEnabledRootView.dispatchTouchEvent (RNGestureHandlerEnabledRootView.java:12)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2845)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2845)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2845)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2845)
  at android.view.ViewGroup.dispatchTransformedTouchEvent (ViewGroup.java:3222)
  at android.view.ViewGroup.dispatchTouchEvent (ViewGroup.java:2845)
  at com.android.internal.policy.DecorView.superDispatchTouchEvent (DecorView.java:697)
  at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent (PhoneWindow.java:1879)
  at android.app.Activity.dispatchTouchEvent (Activity.java:3487)
  at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent (WindowCallbackWrapper.java:2)
  at com.android.internal.policy.DecorView.dispatchTouchEvent (DecorView.java:655)
  at android.view.View.dispatchPointerEvent (View.java:13732)
  at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent (ViewRootImpl.java:6131)
  at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess (ViewRootImpl.java:5909)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:5358)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:5411)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:5377)
  at android.view.ViewRootImpl$AsyncInputStage.forward (ViewRootImpl.java:5536)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:5385)
  at android.view.ViewRootImpl$AsyncInputStage.apply (ViewRootImpl.java:5593)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:5358)
  at android.view.ViewRootImpl$InputStage.onDeliverToNext (ViewRootImpl.java:5411)
  at android.view.ViewRootImpl$InputStage.forward (ViewRootImpl.java:5377)
  at android.view.ViewRootImpl$InputStage.apply (ViewRootImpl.java:5385)
  at android.view.ViewRootImpl$InputStage.deliver (ViewRootImpl.java:5358)
  at android.view.ViewRootImpl.deliverInputEvent (ViewRootImpl.java:8420)
  at android.view.ViewRootImpl.doProcessInputEvents (ViewRootImpl.java:8353)
  at android.view.ViewRootImpl.enqueueInputEvent (ViewRootImpl.java:8306)
  at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent (ViewRootImpl.java:8535)
  at android.view.InputEventReceiver.dispatchInputEvent (InputEventReceiver.java:198)
  at android.os.MessageQueue.nativePollOnce (MessageQueue.java)
  at android.os.MessageQueue.next (MessageQueue.java:326)
  at android.os.Looper.loop (Looper.java:181)
  at android.app.ActivityThread.main (ActivityThread.java:7050)
  at java.lang.reflect.Method.invoke (Method.java)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:494)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```
**Smartphone**
 - OS: Android
 - React Native version: 0.64.0
 - react-native-date-picker: 3.2.10
 - react-native-gesture-handler: 1.10.3

**Comment by Trex28** [comment]
Related to this issue on `react-native-gesture-handler` repo: https://github.com/software-mansion/react-native-gesture-handler/issues/1284

**Comment by ajen010** [comment]
Is there a workaround for this problem? My android simulator and phone crash whenever I touch the datepicker.

**Comment by henninghall** [comment]
Hi! I believe there is a naming collision. Could you help me try this out? Rename the UIManager.java and its references in this project and rebuild.

You can do it in node modules or in android studio.

**Comment by devautor** [comment]
> Hi! I believe there is a naming collision. Could you help me try this out? Rename the UIManager.java and its references in this project and rebuild.
> 
> You can do it in node modules or in android studio.

I am not able to resolve this using this fix. With my limited understanding, I believe this issue is closer to the RN core as being discussed here: https://github.com/facebook/react-native/issues/31245

**Comment by sharifhh** [comment]
Here is a patch-package script as a workaround for now

`diff --git a/node_modules/react-native-date-picker/android/src/main/java/com/henninghall/date_picker/PickerView.java b/node_modules/react-native-date-picker/android/src/main/java/com/henninghall/date_picker/PickerView.java
index 53ee357..de0fcca 100644
--- a/node_modules/react-native-date-picker/android/src/main/java/com/henninghall/date_picker/PickerView.java
+++ b/node_modules/react-native-date-picker/android/src/main/java/com/henninghall/date_picker/PickerView.java
@@ -34,6 +34,7 @@ public class PickerView extends RelativeLayout {
         if (didUpdate(VariantProp.name)) {
             this.removeAllViewsInLayout();
             inflate(getContext(), state.derived.getRootLayout(), this);
+            findViewById(R.id.container).setId(100023);
             uiManager = new UIManager(state, this);
         }
 
`

**Comment by zmtmaster** [comment]
@sharifhh makes sense. Good job. 

This is due to an issue on ReeactNative Core (a new function that was implemented to support FABRIC architecture). 

Error is caused by views that are not directly managed by React Native. In particular, views that are not created by this method:

https://github.com/facebook/react-native/blob/master/ReactAndroid/src/main/java/com/facebook/react/uimanager/ViewManager.java#L140-L141

Since the way ReactNative Core is checking if View is FABRIC or not is being used with the viewId  % 2:
https://github.com/facebook/react-native/blob/24bfa463a7f1b4eac666d038c9d0f919d0cc404f/ReactAndroid/src/main/java/com/facebook/react/uimanager/common/ViewUtil.java#L22

setting the viewId manually to an odd number could solve the issue temporarily.

**Comment by henninghall** [comment]
I don't manage to reproduce this crash 🤔  Would be great if anyone could provide a code sample or explanation of how to reproduce this from an empty project.

**Comment by zmtmaster** [comment]
@henninghall reproduced, minimal repro here: https://github.com/zmtmaster/issue

The crash seems to be happening on only when PanGestureHandler (from `react-native-gesture-handler`) exist, which makes me believe its not an issue with `react-native-date-picker` but with `react-native-gesture-handler`

**Comment by gangstarmn** [comment]
I've same problems. Has anyone solved this problem?

**Comment by zmtmaster** [comment]
> I've same problems. Has anyone solved this problem?

Working on it. Still investigating.

**Comment by zmtmaster** [comment]
Seems that there is a commit on master that should resolve the issue, should be fixed on the next version of react-native (0.65).
https://github.com/facebook/react-native/commit/c317f558f7e5549dffeda1950613ff9844f409e9

**Comment by vsheyanov** [comment]
@sharifhh thanks for the workaround!
Can you explain for a person who doesn't really know the native side, why it works, are there any side effects possible that I should know of?

**Comment by psyzz** [comment]
@sharifhh the patch-package script doesn't work for us, we can scroll the date picker now but still crashing 4/5 times (was 5/5 before ^^)

**Comment by henninghall** [comment]
I also tried @sharifhh's solution and unfortunately still get the crash.

**Comment by ipekmuhammet** [comment]
its happening when you pull wheel diagonal
![image](https://user-images.githubusercontent.com/40898553/121020033-a31dbb80-c7a8-11eb-9795-237c4bac2381.png)

**Comment by henninghall** [comment]
This issue is fixed in react native `0.64.2` 🥳

**Comment by Saad-Bashar** [comment]
Yeah, still happening inside horizontal scroll view :(

**Comment by marwane1b3** [comment]
> Here is a patch-package script as a workaround for now
> 
> ```
> diff --git a/node_modules/react-native-date-picker/android/src/main/java/com/henninghall/date_picker/PickerView.java b/node_modules/react-native-date-picker/android/src/main/java/com/henninghall/date_picker/PickerView.java
> index 53ee357..de0fcca 100644
> --- a/node_modules/react-native-date-picker/android/src/main/java/com/henninghall/date_picker/PickerView.java
> +++ b/node_modules/react-native-date-picker/android/src/main/java/com/henninghall/date_picker/PickerView.java
> @@ -34,6 +34,7 @@ public class PickerView extends RelativeLayout {
>          if (didUpdate(VariantProp.name)) {
>              this.removeAllViewsInLayout();
>              inflate(getContext(), state.derived.getRootLayout(), this);
> +            findViewById(R.id.container).setId(100023);
>              uiManager = new UIManager(state, this);
>          }
>  
> ```

this fixed my problem thank you :)
