### ISSUE TITLE
[Issue on release] it's empty when use as inline-view in  release apk on Android

### ISSUE THREAD

**Issue by annguyen-iosdev** [henninghall/react-native-date-picker#708]
Hi guys, thanks for the new update for the new architecture, I updated the app yesterday, and it looks great when I built it in debug mode, BUT when I generate the release version (.apk for Firebase distribution + .aab for Play Store), it's EMPTY!

![emulator](https://github.com/henninghall/react-native-date-picker/assets/16201598/8a6ff0b5-0a80-41f2-8325-4059e049d2fe)

![android real device](https://github.com/henninghall/react-native-date-picker/assets/16201598/7b6a601a-71e6-4772-9359-5bec55f52f59)

![warning_logs](https://github.com/henninghall/react-native-date-picker/assets/16201598/f68c086e-64d6-4bc3-a1c2-2460c437a90f)

The log every time I open the date picker in debug mode:
```
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `addListener` method.
 WARN  `new NativeEventEmitter()` was called with a non-null argument without the required `removeListeners` method.
...
```
Env: `react-native@0.71.7` + Android API 33

Does anyone face the same issue?

Thanks,

**Comment by annguyen-iosdev** [comment]
Resolved!!!

The issue regards to "default" textColor/theme in the component on Android.

This my mistake, i didn't set textColor/theme. All good now.
Sorry for bothering.

```
<DatePicker style={{width: width}} 
              theme="light"
              textColor="black"
              locale="vi" 
              mode="date"
              date={selectedDate || new Date()} 
              onDateChange={setSelectedDate}
              />
```

**Comment by annguyen-iosdev** [comment]
Resolved!!!

The issue regards to "default" textColor/theme in the component on Android.

This my mistake, i didn't set textColor/theme. All good now.
Sorry for bothering.

```
<DatePicker style={{width: width}} 
              theme="light"
              textColor="black"
              locale="vi" 
              mode="date"
              date={selectedDate || new Date()} 
              onDateChange={setSelectedDate}
              />
```

**Comment by TheMemeLover** [comment]
This did not solve my issue. My code is very simple:
`import { View } from 'react-native';
import React, { useState } from 'react'
import { Button } from 'react-native'
import DatePicker from 'react-native-date-picker'

export default function Home() {
  const [date, setDate] = useState(new Date())
  const [open, setOpen] = useState(false)

  return (
    <View style={{ flex: 1, justifyContent: 'center', alignItems: 'center' }}>
      <Button title="Open" onPress={() => setOpen(true)} />
      <DatePicker
        modal
        open={open}
        date={date}
        onConfirm={(date) => {
          setOpen(false)
          setDate(date)
        }}
        onCancel={() => {
          setOpen(false)
        }}
      />
    </View>
  )}`
I'm using Expo on my android phone and I rebuilt the app multiple times to see if the issue would be resolved but it still gives the same error. I downloaded the latest version of react-native-date-picker.
