### ISSUE TITLE
Bug with maximumDate and datetime mode without using minimumDate

### ISSUE THREAD

**Issue by pelomedusa** [henninghall/react-native-date-picker#755]
**Describe the bug**
On Android, setting the `mode` attribute to `datetime` and the `maximumDate` to `new Date("2024-12-30")` , the Datepicker opens with a minimum date of June 30 2024

The bug might be related to #670 but was not fixed by #740.

**Expected behavior**
The `minimumDate` attribute is **not** used so the date picker should open to the current date without a minimum

**To Reproduce**
Add example code that reproduces the behavior. 
```javascript
import React, {useState} from 'react';
import {
    Button,
    SafeAreaView,
    StyleSheet, Text,


} from 'react-native';

import DatePicker from "react-native-date-picker";


function App(): React.JSX.Element {
  const [value, setValue] = useState(new Date());
  const [open, setOpen] = useState(false);
  const maximumDate = new Date("2024-12-30");

  return (
    <SafeAreaView>

      <Button title={'Open datepicker'} onPress={() => setOpen(true)}/>
      <Text>{maximumDate.toString()}</Text>
      <DatePicker
          modal
          date={value}
          open={open}
          mode={'datetime'}
          maximumDate={maximumDate}
          locale={'en'}
          is24hourSource={"locale"}
          firstDay={1}
          onConfirm={(date) => {
              setValue(date);
              setOpen(false);
          }}
          onCancel={() => {
              setOpen(false)
          }}
      />
    </SafeAreaView>
  );
}

export default App;
```
![image](https://github.com/henninghall/react-native-date-picker/assets/15833842/2c31b83e-631f-4118-9d40-75ec44489b51)

**Smartphone (please complete the following information):**
 - OS: _Android_
 - React Native version: _Tested with 0.71.3 and  0.73.2 (latest)_
 - react-native-date-picker version: _4.3.5_

**Comment by bishoymakkar** [comment]
fixed in release 4.3.6

**Comment by pelomedusa** [comment]
@bishoymakkar unfortunately it looks like the bug is still present in 4.3.6.

**Comment by bishoymakkar** [comment]
fixed in release 4.3.7 confirmed

**Comment by pedrolizi** [comment]
At the moment with version 4.3.7 it is still present. After putting some logs on the DatePickerAndroid.js file it shows the following

`Date { NaN }`

I'm using the Date Picker like this: 

```
<DatePicker
  modal
  locale={ 'es' }
  minimumDate={ new Date() }
  mode="date"
  open={ open2 }
  date={ new Date(input_date_visit) }
  onConfirm={ date => {
    setOpen2(false)
    dispatch(setDateVisit(date))
  } }
  onCancel={ () => {
    setOpen2(false)
  } }
/>
```

and the functions inside the DatePickerAndroid.js file that gets the error are: `_date()` and `_minimumDate()` and that's because both uses the `_toIsoWithTimeZoneOffset()`.

I confirmed that `input_date_visit` it is not a null value on the logic of my component, so that's an unexpected behavior from the package to get a` Date { NaN }` on the function. 

Hope this helps.

**Comment by jaythummar85** [comment]
I have updated defaultNumberOfDays to 10 years, which resolves the issue for the current use case. This serves as an effective interim solution while we evaluate a longer-term implementation if needed.

`node_modules/react-native-date-picker/android/src/main/java/com/henninghall/date_picker/wheels/DayWheel.java`

`private static int defaultNumberOfDays = 360 * 10;`
