### ISSUE TITLE
Error: Unsupported top level event type "spinnerStateChange" dispatched

### ISSUE THREAD

**Issue by sirlojik** [henninghall/react-native-date-picker#777]
![Screenshot_1709611436](https://github.com/henninghall/react-native-date-picker/assets/20199368/326fdb13-00e7-4272-886d-e83256478ba0)

![Screenshot_1709610933](https://github.com/henninghall/react-native-date-picker/assets/20199368/32d3473c-9446-4cb9-a3b2-adabe556de6a)

**Describe the bug**
I am using an inline component as shown in code but when selecting date i get the error above
"Error: Unsupported top level event type "spinnerStateChange" dispatched"

**To Reproduce**
            <DatePicker
              mode={'date'}
              androidVariant="iosClone"
              date={new Date()}
              onDateChange={(date) => {
                console.log(date)
                setStartDate(date);
              }}
            />
```

**Smartphone (please complete the following information):**
 - OS: [Android]
 - react-native: 0.72.6]
 -  "react-native-date-picker": "^4.4.0",

**Comment by henninghall** [comment]
Thanks for reporting this. I will have a look at it, meanwhile you can downgrade to the previous version

**Comment by sirlojik** [comment]
Thanx for quick reply. I used v4.2.7 and it worked

**Comment by MayurMax4** [comment]
getting same issue with latest version, please update once it is fixed

**Comment by OrangeFrodo** [comment]
Same error, fixed by downgrading to 4.3.7

**Comment by henninghall** [comment]
Haven't been able to reproduce the issue, but might have a fix ready.

Can someone try version `4.4.1-alpha.0` and let me know if it solved the issue?

**Comment by himangi14** [comment]
@henninghall  tried with 4.4.1-alpha.0. having same issue **_Error: Unsupported top level event type "spinnerStateChange" dispatched, js engine: hermes_**

**Comment by Luckfried** [comment]
@henninghall also downgrades did not work for me.

**Comment by dryusha** [comment]
> Haven't been able to reproduce the issue, but might have a fix ready.
> 
> Can someone try version `4.4.1-alpha.0` and let me know if it solved the issue?

For me, it works well right now with this alpha version.. thx

**Comment by henninghall** [comment]
> @henninghall tried with 4.4.1-alpha.0. having same issue **_Error: Unsupported top level event type "spinnerStateChange" dispatched, js engine: hermes_**

Did you rebuild the app?

**Comment by Luckfried** [comment]
deleted evey cache file and removed node_modules and yarn.lock. Now it works with the alpha version. 👍

**Comment by erickcrus** [comment]
same here

> deleted evey cache file and removed node_modules and yarn.lock. Now it works with the alpha version. 👍

this dont work for me.

Im using this version:
"react-native-date-picker": "^4.1.3"

My code `onDateChange` prop just call `setDate` to handle view state.
This has always worked, but in the last build, I noticed some crash logs triggering this error in production, for example:
```
const initialValue = "2024-03-10T16:00:27.218Z";

const FooComponent = () => {
   const [date, setDate] = useState(new Date(initialValue ?? ''));

   return <View>
      <DatePicker date={date}
         mode='date'
         androidVariant='iosClone'
         onDateChange={setDate}
         fadeToColor='none'
         textColor={theme.colors.fontPrimary}
         style={{ width, backgroundColor: theme.colors.card }} />
   </View>
}

export default FooComponent;
```

**Comment by timmylindh** [comment]
> @henninghall tried with 4.4.1-alpha.0. having same issue **_Error: Unsupported top level event type "spinnerStateChange" dispatched, js engine: hermes_**

I can confirm it working in 4.4.1-alpha.0. Will be running this until a new version is released.

**Comment by timmylindh** [comment]
> Haven't been able to reproduce the issue, but might have a fix ready.
> 
> Can someone try version `4.4.1-alpha.0` and let me know if it solved the issue?

I can confirm it working in 4.4.1-alpha.0. Will be running this until a new version is released.

**Comment by alperpacin** [comment]
I can also verify that 4.4.4.1-alpha.0 works without any problem.

**Comment by Chbilalramzan** [comment]
I used v4.2.7 and it worked for me

**Comment by aishevdt12** [comment]
i am using  npm i react-native-date-picker@4.3.7 then fixed my issue

**Comment by MeAbhinavsharma** [comment]
i try every solution  **@aishevdt12 @Chbilalramzan @alperpacin** @Luckfried  but not working .can you **@henninghall**  provide me another solution.

**Comment by BeerensJian** [comment]
In version 4.4.1 this is still an issue, the error doesnt happen on version 4.3.7 and below

<DatePicker androidVariant="nativeAndroid" mode="time" date={datetime} onDateChange={setdatetime} is24hourSource="locale"/>

**Comment by hamxahussain** [comment]
getting same error even after upgrading to alpha version
`Error: Unsupported top level event type "spinnerStateChange" dispatched, js engine: hermes`

**Comment by Chbilalramzan** [comment]
@MeAbhinavsharma  @hamxahussain you need to check the react-native version of your project then choose the version of react-native-date-picker respectively. May be then it will work.

**Comment by hamxahussain** [comment]
> @MeAbhinavsharma @hamxahussain you need to check the react-native version of your project then choose the version of react-native-date-picker respectively. May be then it will work.

yeah the alpha version works every where accept with old react native, which I made a tiny mistake in linking, Thanks now its working

**Comment by Chbilalramzan** [comment]
I'm pleased to hear that it's working for you.

**Comment by timmylindh** [comment]
Is the fix pushed as of now?

**Comment by gimi-anders** [comment]
> @MeAbhinavsharma @hamxahussain you need to check the react-native version of your project then choose the version of react-native-date-picker respectively. May be then it will work.

I am still getting this issue on 4.4.1. 
How do I know what version of react-native I need? (I am using 0.71.13)

**Comment by hamxahussain** [comment]
The React Native Version doesn't matter as far as I know, But the `"react-native-date-picker": "^4.4.1"` matters, Try running these commands, then checkout that helps are not.
`yarn add react-native-date-picker@4.4.0-alpha.0`
`yarn start --reset-cache`
`yarn android` OR `yarn ios`

**Comment by gimi-anders** [comment]
Thanks, I thought the fix was included in 4.4.1. Hope it will make it into 4.4.2.

**Comment by henninghall** [comment]
The fix did not make it into 4.4.1. Now version 4.4.2 is released, could anyone with the error test it out? (remember to rebuild)

**Comment by mduthilleul** [comment]
4.4.2 is resolving the issue for me.
Thanks for the fix !
