### ISSUE TITLE
title text in dark mode under Android is too dark to be legible and the color is not manually configurable

### ISSUE THREAD

**Issue by rubenjavier** [henninghall/react-native-date-picker#829]
**Describe the bug**
The title text in dark mode under Android is too dark to be legible and the color is not manually configurable

**Expected behavior**
The title text should be legible in dark theme or better yet, the title text color and modal background color should be configurable
ideally we should have the following colors to be configurable
titleColor
backgroundColor

Thanks in advance.

**To Reproduce**
set theme to dark in android 14

**Smartphone (please complete the following information):**
 - OS: [Android]
 - React Native version [e.g. 0.73.6]
 - react-native-date-picker version [e.g. 5.0.4]

**Comment by Georg7** [comment]
Same issue here. Only on Android (modal mode)
![IMG_1613](https://github.com/henninghall/react-native-date-picker/assets/7827962/35ff63c6-9608-4eb8-91c5-cd40dbb12e28)

**Comment by mkhoussid** [comment]
Is this library no longer maintained? Many issues opened regarding dark mode

**Comment by henninghall** [comment]
Fixed in v5.0.6

**Comment by Georg7** [comment]
> Fixed in v5.0.6

I've just upgraded to v5.0.7 but still having the same issue. What's worse the action buttons are now also not adapting to dark mode anymore. 

![IMG_2194](https://github.com/user-attachments/assets/1c89cbd5-94a6-4bac-b297-3de068e8458c)


`<DatePicker
						date={date}
						onDateChange={setDate}
						mode="time"
						modal={true}
						confirmText={t("common.actions.confirm")}
						cancelText={t("common.actions.cancel")}
						title={t("common.actions.selectTime")}
						locale={i18n.language}
						open={pickerOpen}
						textColor={Colors[colorScheme].primary}
						theme={"dark"}
						dividerColor={Colors[colorScheme].secondary[100]}
						minuteInterval={15}
						onConfirm={handlePickerConfirm}
						onCancel={() => setPickerOpen(false)}
					/>`

**Comment by henninghall** [comment]
@Georg7 Did you rebuild the app? EBay android version are you using?

**Comment by Georg7** [comment]
> @Georg7 Did you rebuild the app? What android version are you using?

Yes, rebuilt the app. Title works correctly but action buttons in dark mode still don't work (black colour on dark background). Android 13.

**Comment by ericpoulinnz** [comment]
@henninghall any update here? This also happens for me on version 5.0.7.

The Divider seems to adapt to the theme color, but the title and buttons do not.
