### ISSUE TITLE
Error: Exception in HostFunction: Non-whitespace character found after end of conversion: "-07-10T12:51:52.881Z"

### ISSUE THREAD

**Issue by bnv1223** [henninghall/react-native-date-picker#840]
Getting the error :
Error: Exception in HostFunction: Non-whitespace character found after end of conversion: "-07-10T12:51:52.881Z"

 "react": "18.2.0",
  "react-native": "0.74.1",
  "react-native-date-picker": "^5.0.4",

**Comment by badrey** [comment]
I made a fix which works for me. Had the same issue with new architecture enabled on Android
https://github.com/henninghall/react-native-date-picker/pull/848

**Comment by pasindupansiluvault** [comment]
> Please provide example code where this issue is reproducible and I'll look into it

So the issue happens when using the component with **modal={false}** and **newArchEnabled=true**

**Comment by brentkelly** [comment]
@henninghall this happens for me with just the default inline example:

```javascript
import React, { useState } from 'react'
import DatePicker from 'react-native-date-picker'

export default () => {
  const [date, setDate] = useState(new Date())

  return <DatePicker date={date} onDateChange={setDate} />
}
```

New architecture enabled. Relevant packages:

```
"react": "18.2.0",
"react-native": "~0.75.0",
"react-native-date-picker": "^5.0.7",
```

**Comment by shel404** [comment]
Facing the same issue while using inline mode with newArchEnabled

**Comment by szarbartosz** [comment]
Having the same issue (old arch) - @henninghall are there any updates on this one? 🙏

**Comment by SzymonGonet** [comment]
Same issue... @henninghall any updates on this one?

**Comment by Mateo-Abribat** [comment]
Same issue ! @henninghall

**Comment by lpcapestanya** [comment]
same issue here, is there any solution ?

**Comment by swoo888** [comment]
for people get stuck by this error, Badrey made a fix for this. see comments above.  To use the fix, edit package.json dependency section to use this line below, and it will pull in Badrey's fix.  
"react-native-date-picker": "git+https://github.com/badrey/react-native-date-picker.git#new-arc-fix"

**Comment by mateoabrbt** [comment]
Hello for me it was French !

**Comment by brentkelly** [comment]
> Hi guys I’ll look into this, which device languages is active when this happens?

@henninghall FYI for me it was just the default inline example in English.

**Comment by RamProg** [comment]
Same error here!

**Comment by agag4** [comment]
i have same issue, is there any solution ??

**Comment by luisnquin** [comment]
Same here

**Comment by OldsunFlush** [comment]
Same here. Even with the fix, the app crashes on date change.

**Comment by adblanc** [comment]
@OldsunFlush I had the same issue at first and it was because I forgot to rebuild the app, now it seems to works smoothly even on date change with the fix 👍

**Comment by ilteoood** [comment]
I have the same issue and I confirm that patching the package using @badrey's PR worked on my app with the native architecture enabled.

**Comment by henninghall** [comment]
I have been able to reproduce this in new architecture (bridgeless) with expo 52. 

I appreciate @badrey 's solution, but unfortunately it is not something we can merge at the moment. 

I've made a [draft PR ](https://github.com/henninghall/react-native-date-picker/pull/873) of the approach we would need, if anyone got the time, please pick it up from there and complete it. Make it compile and test it out. I will have limited internet access until end of januari but I will be able to review and merge PRs.

Thanks guys!

**Comment by OldsunFlush** [comment]
Indeed, it seems to works after a rebuild!

**Comment by sabinayakc** [comment]
Having the same issue. Currently using @badrey's solution until this gets fixed upstream.

**Comment by cebrakadabra** [comment]
I applied it as a patch for now to fix it in the new architecture (RN0.76.3), (react-native-date-picker ^5.0.7).
(only needed for android, as pointed out)

#### Step 1:
Edit the package as described in #848, paths:
```
./node_modules/react-native-date-picker/android/src/main/java/com/henninghall/date_picker/Utils.java
./node_modules/react-native-date-picker/src/DatePickerAndroid.js

```

#### Step 2:
Install patch-package
```
npm install patch-package -D 
```

or via yarn
```
yarn add patch-package postinstall-postinstall --dev
```

#### Step 3:
add the postinstall script in your package.json
```
"scripts": {
  "postinstall": "patch-package"
 }
```

#### Step 4:
Create the patch file
```
npx patch-package react-native-date-picker
```

or 

```
yarn patch-package react-native-date-picker
```

#### Step 5:
This will produce a file in your `./patches` directory

#### Step 6:
Apply the patch
```
npm install or yarn
```

#### Step 7:
Add your staged changes
```
git add .
git commit ...
git push origin ...
```

**Comment by baicuhaha** [comment]
I still have the same issue. Can the official release solve this problem? I'm just using it in a simple way.
  const [date, setDate] = useState(new Date());
    <DatePicker date={date} onDateChange={setDate} />

**Comment by vishalkpiv** [comment]
I  am facing the same error is there any there update regarding that or have to use @badrey 's solution ??

**Comment by wow64cpu** [comment]
Hi, I used the solution @badrey  and it works

I used it this way https://github.com/henninghall/react-native-date-picker/issues/840#issuecomment-2450405601

When will the fix be included in the release?

**Comment by UmarbekSaidov** [comment]
same issue here, is there any solution ?

**Comment by UmarbekSaidov** [comment]
> for people get stuck by this error, Badrey made a fix for this. see comments above. To use the fix, edit package.json dependency section to use this line below, and it will pull in Badrey's fix. "react-native-date-picker": "git+https://github.com/badrey/react-native-date-picker.git#new-arc-fix"

it worked, thank you

**Comment by henninghall** [comment]
The issue has been resolved in version 5.0.9. Please consider sponsoring the package to support this work 🩷

**Comment by xshinigamiy** [comment]
@henninghall : We still see this issue in the latest version 5.0.10, would really appreciate if the changes are tested in Android device. I appreciate your hardwork and dedication in maintaining this library.

**Comment by sealabcore** [comment]
We are also still seeing this error on the latest version 5.0.10.

**Comment by xshinigamiy** [comment]
> We are also still seeing this error on the latest version 5.0.10

I was able to fix the issue with [this](https://github.com/xshinigamiy/react-native-date-picker/pull/1/files) and [this](https://github.com/xshinigamiy/react-native-date-picker/pull/2) MR

**Comment by jakubperdoch** [comment]
Still having same issue, is there any solution ?

**Comment by BharatEdu97** [comment]
Downgrade and use 5.0.9 Until its resolved

**Comment by OldsunFlush** [comment]
Even with v5.0.9 after rebuilding, I have to use `"react-native-date-picker": "git+https://github.com/badrey/react-native-date-picker.git#new-arc-fix"` in my `package.json` for the package to work on Android (it doesn't throw errors on emulators).

**Comment by alexcraviotto** [comment]
Yeah, still having this issue.

Using now "react-native-date-picker": "git+https://github.com/badrey/react-native-date-picker.git#new-arc-fix"
