### ISSUE TITLE
[Bug]: Immediate crash when rendering DatePicker (only on DEV, iOS)

### ISSUE THREAD

**Issue by laurens-lamberts** [henninghall/react-native-date-picker#919]
### Describe the bug

Only when running on iOS in development mode, the app crashes when the date picker renders. Leaving out the date picker fixes the app, and when I make a release build including the date picker, it just works.

The crash happens both on simulator and real device, but is not faced on Android. Both date picker and time picker face the crash.
So only on iOS in development mode, the app crashes.

The full crash report from Apple is attached.
[crashlog.txt](https://github.com/user-attachments/files/20575053/crashlog.txt)

### Expected behavior

The app should not crash.

### To Reproduce

```javascript
Init a new Expo project, and run it on iOS with development build (not Expo Go).
Add a date picker to your code, and the app will instantly crash whenever the date picker is being rendered.
```

### Operating System

- [ ] Android
- [x] iOS

### React Native Version

0.79.2

### Expo Version (if applicable)

53.0.9

### react-native-date-picker version

5.0.12

### React Native Architecture

- [ ] Old Architecture (Paper)
- [x] New Architecture (Fabric)

### Relevant log output

```shell

```

**Comment by laurens-lamberts** [comment]
If it helps, I could make a fresh Expo init repo with date picker in it, to demonstrate the crash.
Just let me know if this is helpful.

**Comment by michbil** [comment]
The error i'm getting in the console is following
```
[CoreFoundation] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[RNDatePicker setMinuteInterval:]: unrecognized selector sent to instance 0x16b261b00'
*** First throw call stack:
(
0   CoreFoundation                      0x000000011718c10c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x0000000104feeda8 objc_exception_throw + 72
2   CoreFoundation                      0x00000001171a1bf4 +[NSObject(NSObject) instanceMethodSignatureForSelector:] + 0
3   UIKitCore                           0x000000014a1fa940 -[UIResponder doesNotRecognizeSelector:] + 232
4   CoreFoundation                      0x000000011719040c ___forwarding___ + 1268
5   CoreFoundation                      0x0000000117192b2c _CF_forwarding_prep_0 + 92
6   C3G.debug.dylib                     0x000000010b19fd04 __49-[RCTComponentData createPropBlock:isShadowView:]_block_invoke_10 + 388
7   C3G.debug.dylib                     0x000000010b1a0f60 __49-[RCTComponentData createPropBlock:isS<…>
```

**Comment by michbil** [comment]
Looks like some issue with codegen

Adding line to ios/build/generated/ios/RCTThirdPartyComponentsProvider.mm fixes issue, picker works again
```
	@"RNDatePicker": NSClassFromString(@"RNDatePicker"), // @react-native-community/slider
```

**Comment by michbil** [comment]
@laurens-lamberts Amazing patch, applied it and it works for me too

Temporarily added this patch to my pnpm setup to unblock further development:
```
diff --git a/package.json b/package.json
index 642788b4bbc398a34b8185e40ff54a443fe5ac19..d92ba66d2063585aa32c23ffcf39562e8105eb9b 100644
--- a/package.json
+++ b/package.json
@@ -66,6 +66,11 @@
     "jsSrcsDir": "src/fabric",
     "android": {
       "javaPackageName": "com.henninghall.date_picker"
+    },
+    "ios": {
+      "componentProvider": {
+        "RNDatePicker": "RNDatePicker"
+      }
     }
   }
 }
```

**Comment by henninghall** [comment]
Thanks for reporting and investigating this. A fix is released in version 5.0.13

**Comment by hoerlanton** [comment]
Hi guys!
I still have this issue although I am on 5.0.13.

Here the error log: 

> Exception thrown while executing UI block: -[RNDatePicker setMinuteInterval:]: unrecognized selector sent to instance 0x149a2e5a0
> 
> __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke
>     RCTUIManager.mm:1169
> __44-[RCTUIManager flushUIBlocksWithCompletion:]_block_invoke.195
> __RCTExecuteOnMainQueue_block_invoke
> _dispatch_call_block_and_release
> _dispatch_client_callout
> _dispatch_main_queue_drain.cold.7
> _dispatch_main_queue_drain
> _dispatch_main_queue_callback_4CF
> __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__
> __CFRunLoopRun
> CFRunLoopRunSpecific
> GSEventRunModal
> -[UIApplication _run]
> UIApplicationMain
> __debug_main_executable_dylib_entry_point
> start_sim
> 0x0

 react-native:
    installed: 0.79.3
iOS:
  hermesEnabled: true
  newArchEnabled: true
  "@react-native-community/cli":
    installed: 18.0.0
  react:
    installed: 19.0.0

Basic implementation:

`  <DatePicker
                date={new Date()}
                mode="datetime"
            />`


What further information should i provide?

**Comment by ankitpunchh** [comment]
Same issue from no where. Any solution ?

**Comment by metinaltinbas** [comment]
> Thanks for reporting and investigating this. A fix is released in version 5.0.13

 "react-native": "0.80.2",
 "react-native-date-picker": "5.0.13",

doesn't work well together , if i downgrade this issue also appears.

**Comment by Resource-4** [comment]
@metinaltinbas same happening with me too, getting the Module provider RNDatePickerManager does not conform to RCTModuleProvider in 5.0.13 and when downgrade the version, get crash.

**Comment by kamalsfahr** [comment]
Same issue "Module provider RNDatePickerManager does not conform to RCTModuleProvider" after upgrading to 5.0.13 in RN0.81.5

**Comment by davortrifunov** [comment]
Same issue here as well, any fixes ?

**Comment by jaikantshikray** [comment]
@kamalsfahr did u find any solution ?

**Comment by Reykjavik151** [comment]
Upgrade from 5.0.12 to 5.0.13 worked for me.

**Comment by Reykjavik151** [comment]
> Same issue "Module provider RNDatePickerManager does not conform to RCTModuleProvider" after upgrading to 5.0.13 in RN0.81.5

I think you need clean the cache and try again.

**Comment by laurens-lamberts** [comment]
@henninghall This is still an issue for me.
I've got bundler cache and native folders cleared before testing, and currently run the following versions;

Expo: `54.0.33`
React Native: `0.81.5`
react-native-date-picker: `5.0.13`

The error still displays at DEV app startup (only dev), is dismissible and the date picker just works fine afterwards. Here's a screenshot.

Is there something I should configure differently, or should we reopen this issue?

<img width="1206" height="2622" alt="Image" src="https://github.com/user-attachments/assets/c950b340-e152-4f86-a065-733130c80d81" />
